# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT
#
# For documentation on the github environment, see
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
#
# For documentation on the syntax of this file, see
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

# This action will run doxygen to update the documentation at https://microsoft.github.io/ebpf-for-windows/
# which is a view of the gh-pages branch.  This action is done whenever the main branch is updated.
# For docs on gh-pages see https://pages.github.com/
#
# The following two links discuss steps similar to this action so may be useful reading
# to understand how the automatic update works:
#  https://growworkinghard.altervista.org/doxygen-documentation-on-github-using-gh-pages/
#  https://github.com/m-a-d-n-e-s-s/madness/issues/104

name: Doxygen Action

# Controls when the action will run. Triggers the workflow on push events
# but only for the main branch.
on:
  push:
    branches: [ main doxygen ]

# Declare default permissions as read only.
permissions: read-all

jobs:
  build-and-deploy:
    permissions:
      contents: write  # Needed to git push.
    runs-on: ubuntu-latest

    steps:

    - name: Install doxygen
      run: |
        sudo apt install doxygen

    # Check out (non-recurisvely) the ebpf-for-windows main branch.
    - name: Checkout
      uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5

    # Create doxygen docs under the docs/html subdirectory.
    - name: Build docs
      run: |
        doxygen

    # Check docs into the gh-pages branch to deploy them to the live website.
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs/html # The folder the action should deploy.
        token: ${{ secrets.GITHUB_TOKEN }}
        git-config-name: Github Action
        git-config-email: ebpf-for-windows@users.noreply.github.com
